version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api1
      - api2
      - postgres

  api1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    command: yarn start
    depends_on:
      - postgres

    
  api2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    command: yarn start
    depends_on:
      - postgres

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xmx512m -Xms512m"
    ports:
      - "9200:9200"
      - "9300:9300"

  postgres:
    image: postgres:latest
    container_name: pg-container
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data