version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api1
      - api2

  api1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    command: yarn start
    
  api2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    command: yarn start
    